### ISSUE TITLE
cyipopt 1.0.3 running VERY slowly on Windows 10 and conda  4.10.1

### ISSUE THREAD

**Issue by agrishin** [mechmotum/cyipopt#114]
I have a sparse nonlinear system (1600 variables) I've optimized quickly in the past using a previous version of cyipopt (0.1.7). Using the latest install on anaconda, it runs at least an order of magnitude more slowly. Previously, the MUMPS solver never had to increase the memory, but now it increases it several times.
Again, this is the same model. Any tips, hints, or suggestions? Any way to adjust solver settings to run more like the previous version?

**Comment by brocksam** [comment]
Are you able to provide any more details please? Specifically some information on the output from IPOPT and ideally a comparison between the problem running quickly using cyipopt 0.1.7 and slowly using cyipopt 1.0.3. Can you also please provide details about how you installed cyipopt 0.1.7? And confirm whether cyipopt 1.0.3 was install completely using conda (including all dependencies, e.g. Ipopt)?

**Comment by agrishin** [comment]
Nevermind. Looking closer, it appears that the two cases I reference aren't the same. The new case has twice the number of variables (3200). Still, it's disappointing that it runs so slowly. I was also wrong in claiming that the smaller model running in version 0.1.7 didn't have to reallocate more memory. It also did several times (and the same amount). This just wasn't obvious earlier because I was running the model in an import from spyder (where you can't see the ipopt output). I'm now trying to do the comparison you suggest on each of the two models, but I find that I can't run ipopt from the console in the newer build (1.0.3). When I try, I get the following error:
FileNotFoundError: Could not find module 'C:\ProgramData\Anaconda3\lib\site-packages\scipy\.libs\libbanded5x.3OIBJ6VWWPY6GDLEMSTXSIPCHHWASXGT.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by agrishin** [comment]
Ok. this last issue is apparently produced after un-installing anaconda, re-installing, issuing conda update --all, followed by conda install -c conda-forge cyipopt. This sequence appears to somehow uninstall scipy (that's ultimately the source of the error cited above). 
If I skip the update --all after re-installing anaconda, I find that ipopt seems to install and run as expected. But now I see my original posted issue again. This time, I'm running my better behaved smaller model (1600 variables), and it does indeed run differently (longer and many more iterations) on the newer ipopt build.  I have included the ipopt output for both runs (again, same model: different environments). The file "old_out.txt" is the output I get for the older build (version 0.1.7), while "new_out.txt" is the output I get for newer build (version 1.0.3).
[new_out.txt](https://github.com/mechmotum/cyipopt/files/6339596/new_out.txt)
[old_out.txt](https://github.com/mechmotum/cyipopt/files/6339597/old_out.txt)

**Comment by agrishin** [comment]
Sorry to keep responding to my own post, but I think I've found (and fixed) my perceived discrepancy between the smaller model (1600 variables) running in version 0.1.7 and 1.0.3. There was yet another small difference between the model I ran in 0.1.7 and the one I ran in 1.0.3. Bottom line: I'm running a topology optimization study. I build a finite element model and solve it at each iteration. The subtle issue here is that I was using a projection scheme at each iteration in the version running on 1.0.3, and not the earlier one (I overlooked this earlier). Apparently, the IPOPT solver really doesn't like that. Anyway, when I remove that, I get very similar results on 1.0.3 vs. 0.1.7. See the attached output "new_out2.txt" (note the runtime of 103s vs. 85s in "old_out.txt").
Ok, but now when I go to a similar model (same model problem, but now meshed using triangles vs quadrilaterals. This is the model that caused me concern originally when I mistakenly thought I was running the smaller model), the number of variables doubles, but the run-time increases by almost a factor of 40 (as you can see in the output "LargeModel.txt").

So, my issue now is NOT a question of why version 1.0.3 runs more slowly than 0.1.7, but rather, why does IPOPT (any version) take almost 40 times longer to run a problem twice as large (same physics)...?

[new_out2.txt](https://github.com/mechmotum/cyipopt/files/6340323/new_out2.txt)
[LargeModel.txt](https://github.com/mechmotum/cyipopt/files/6340330/LargeModel.txt)

**Comment by moorepants** [comment]
@agrishin Thanks for this info. cyipopt is a very thin layer on top of IPOPT and there isn't much performance critical code in cyipopt. Any slowness likely comes from IPOPT and it's dependencies. If you are using conda to install the conda-forge packages, then the speed can depend on how the packages are built in the relevant conda forge feedstocks. And, as you've discovered, the speed depends on your problem and how you set it up for ipopt. For these problem specific issues, getting help on the ipopt communication channels is probably the best bet. Also, look into profiling your constraint, objective, gradient, jacobian and, hessian functions.

I'm going to close this issue, given the updates above. Please reopen if needed.
