### ISSUE TITLE
difficulty with cyipopt installation

### ISSUE THREAD

**Issue by solenedp** [mechmotum/cyipopt#116]
Hi everyone,
I try to install cyipopt on Windows using conda and the "conda install -c conda-forge cyipopt" command, but I get this error:

```
InvalidArchiveError("Error with archive C:\\Users\\Solène Delannoy-Pavy\\.conda\\pkgs\\conda-4.10.1-py38h9f7ea03_1qg3n0n0f\\info-conda-4.10.1-py38h9f7ea03_1.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nFailed to open 'C:\\Users\\Solène Delannoy-Pavy\\.conda\\pkgs\\conda-4.10.1-py38h9f7ea03_1qg3n0n0f\\info-conda-4.10.1-py38h9f7ea03_1.tar.zst'")
```

I read it might be because the name of the directory were anaconda is located contains a space. So I tried to change the name but the same problem occurs. I also tried to use the "anaconda clean -a" command before installing cyipopt but it doesn't change anything. Do you have any idea? I thank you a lot in advance!

**Comment by moorepants** [comment]
Is this the only package you can't install via conda?

**Comment by moorepants** [comment]
It isn't clear why you are getting a `.zst` file. The files available are all `.bz2`: https://anaconda.org/conda-forge/cyipopt/files

**Comment by moorepants** [comment]
Try installing in a new environment:

```
conda create -n cyipopt-env -c conda-forge cyipopt
conda activate cyipopt-env
python -c "import cyipopt"
```

**Comment by moorepants** [comment]
This says to use `conda clean -a` https://stackoverflow.com/questions/59657306/invalidarchiveerror-when-executing-conda-install-notebook

**Comment by moorepants** [comment]
Maybe this: https://stackoverflow.com/questions/61726576/i-am-getting-an-invalidarchiveerror-in-anaconda-prompt-when-i-am-trying-to-insta

You may get better help asking conda or conda forge people. Seems like an error with the install tools, not cyipopt (as a first guess).

**Comment by moorepants** [comment]
Closing this since there has been no response. Reopen if you have more questions.
