### ISSUE TITLE
How to get PARDISO solver to work under linux? (undefined symbol: omp_in_parallel)

### ISSUE THREAD

**Issue by tobias-kies-artemis** [mechmotum/cyipopt#118]
When I try to run `cyipopt` with the `pardiso` linear solver, then I get an error `undefined symbol: omp_in_parallel`. Is there a trick how I can get the PARDISO solver to work?

# My environment
* Debian Linux
* Python 3.9.6
* cyipopt version 1.0.3 from conda-forge
* I have both a `libhsl.so` and `libpardiso.so` available

# Minimal Example and Output
```python
# For this test it is assumed that libhsl.so, libpardiso.so and
# pardiso.lic are stored in the current directory.
# Under this assumption, you can run this script by executing
# the following command:
# LD_LIBRARY_PATH=$(pwd) python sample.py

import cyipopt
import numpy as np

class ProblemDefinition:
    def __init__(self):
        dummy_scalar = lambda *args, **kwargs: 1
        dummy_array = lambda *args, **kwargs: np.array([1])
        self.objective = dummy_scalar
        self.gradient = dummy_array
        self.constraints = dummy_array
        self.jacobian = dummy_array
        self.jacobian_structure = dummy_array
        self.hessian = dummy_array
        self.hessian_structure = dummy_array


problem_definition = ProblemDefinition()
x0 = [1]
nlp = cyipopt.Problem(n=1, m=1, problem_obj=problem_definition, cl=[1], cu=[1])
for solver in ["mumps", "ma27", "ma57", "pardiso"]:
    print("Using solver", solver)
    nlp.add_option("sb", "yes")
    nlp.add_option("max_iter", 1)
    nlp.add_option("print_level", 1)
    nlp.add_option("linear_solver", solver)
    _, info = nlp.solve(x0)
    print(f"Final status {info['status']} ({info['status_msg'].decode()})")
    print()
```

This generates the following output:

```
Using solver mumps
Final status 0 (Algorithm terminated successfully at a locally optimal point, satisfying the convergence tolerances (can be specified by options).)

Using solver ma27
Final status 0 (Algorithm terminated successfully at a locally optimal point, satisfying the convergence tolerances (can be specified by options).)

Using solver ma57
Final status 0 (Algorithm terminated successfully at a locally optimal point, satisfying the convergence tolerances (can be specified by options).)

Using solver pardiso
Exception of type: DYNAMIC_LIBRARY_FAILURE in file "../../src/Common/IpLibraryLoader.cpp" at line 67:
 Exception message: /home/myuser/libpardiso.so: undefined symbol: omp_in_parallel
Final status -12 (Invalid option encountered.)
```

I.e., everything works, but PARDISO triggers an OpenMP-related error.

# What else I tried
* I compiled IPOPT from source (using the latest version on GitHub) and use PARDISO directly via the C interface. However, for this to work I had to make sure that IPOPT is built with he `-fopenmp` flag.
* I then built cyipopt from source using my self-compiled version of IPOPT. However, I still got stuck with the same issue.

Are there some special requirements that need to be posed on `libpardiso.so` in order for it to work with cyipopt?

**Comment by moorepants** [comment]
This might be helpful:

https://github.com/conda-forge/ipopt-feedstock/pull/65

A contributor is adding paradiso if mkl is installed there. They have it working.

**Comment by moorepants** [comment]
These kinds of questions are better asked to the IPOPT discussion channels. Getting IPOPT compiled in custom ways is not something we really support here, but maybe someone has some tips.

**Comment by moorepants** [comment]
There may be some clues in some of these posts that Google finds: https://www.google.com/search?hl=en&q=pardiso%20omp_in_parallel

**Comment by tobias-kies-artemis** [comment]
Thanks for the hints! I'll keep digging.

I am able to use the PARDISO solver when using IPOPT directly. I did have to compile IPOPT with the `-fopenmp` flag (and of course set the correct paths such that IPOPT can find the PARDISO shared library and license file), but I am able to compile and successfully run C programs which use IPOPT and PARDISO. So, the "custom IPOPT build" part is (hopefully) resolved for me.

The thing that I sadly cannot get to work still is to call PARDISO through cyipopt. I even built cyipopt from source myself (linking to my custom built IPOPT library) but that did not resolve the issue for me either.

In general, there seem to be only very few resources pointing to this kind of issue, and - in more general contexts - it mostly appears to relate to OpenMP not being linked properly. In that sense I tried passing some `-fopenmp` flags to the Cython build step (although the default build params actually look like they should work already), but that did not yet do the trick for me either (but that's maybe a topic which could I investigate further).

In that sense, and before going into any very deep details, I just wanted to ask on a high level: Do you happen to know if it "usually" works for people to call PARDISO via cyipopt (preferably under Linux and maybe even using the "pre-made" conda package), or is this potentially a somewhat more exotic/unusual use case for this package?

**Comment by moorepants** [comment]
I don't recall anyone else reporting anything about pardiso here. From the conda-forge PR I saw someone said there have been some updates in IPOPT 3.14 regarding pardiso, so maybe this is a new issue. You could try compiling an older IPOPT.

If cyipopt can't use the pardiso solver, it is an issue that needs to be resolved here. Someone would need to figure it out and suggest a solution. I personally don't know as I've never used that solver.

**Comment by tobias-kies-artemis** [comment]
Thanks for the info! I think I finally got it to work.

Somebody gave me a hint to try working with the `LD_PRELOAD` variable. What I had to do was to "manually" point my Python environment to the correct OpenMP and LAPACK library paths that IPOPT expects to get.

How I did it more specifically:
* I ran `cd / && find . -name "libipopt.so" 2> /dev/null` to find the location of the IPOPT shared library on the system (there probably is a prettier way to do this). I ended up finding it in some `.../miniconda3/envs/{ENVIRONMENT_NAME}/lib` directory.
* I switched into that directory and ran `ldd libipopt.so`. From there the lines containing "libgomp" and "liblapack" where the most important.
* I added these two paths "manually" to the LD_PRELOAD variable before calling Python. My command ended up looking like this:
```sh
LD_PRELOAD="/path/to/miniconda3/envs/env_name/lib/././liblapack.so.3:/path/to/miniconda3/envs/env_name/lib/./././libgomp.so.1" python script.py
```

From that, I'd *assume* that the issue is more closely related to the actual Python environment rather than cyipopt itself. I am not sure yet how to make this prettier or why this is happening in the first place, so I am very open to improvement suggestions. But besides that, I am happy that it works at all, and maybe this will be useful information for other people in the future.

With that I'd also consider the issue resolved.

**Comment by moorepants** [comment]
Great!

We're using pkg-config on linux and mac to set the correct compiler flags. Maybe some improvement to that could make this easier.

**Comment by kwmcbride** [comment]
I am having the exact same issue, but when trying to use the HSL packages. My custom version of IPOPT works fine, but when using the same IPOPT installation with cyipopt, it cannot find the HSL linear solvers. I will try to use the solution posted above to see if it works for me.

**Comment by xiao-wang007** [comment]
> I am having the exact same issue, but when trying to use the HSL packages. My custom version of IPOPT works fine, but when using the same IPOPT installation with cyipopt, it cannot find the HSL linear solvers. I will try to use the solution posted above to see if it works for me.

did it work for you?
