### ISSUE TITLE
Support for Derivative checker

### ISSUE THREAD

**Issue by abelinsky** [mechmotum/cyipopt#127]
As a convenient feature, Ipopt provides the option to run a simple derivative checker, based on finite differences, before the optimization is started.
To use the derivative checker, it is possible to use the option derivative_test. While we can use this option in cyipopt, there is no way to output this information. Are you planning to add this option to cyipopt?

**Comment by brocksam** [comment]
There is currently no plan to add this in the immediate future. However, we'd very much welcome a PR enabling CyIpopt to support this functionality. Perhaps you'll like to give this a go? We'd be happy to answer any questions to help along the way :)

**Comment by moorepants** [comment]
The output of the derivative checker is displayed to stdout if you enable the option. Are you requesting that cyipopt capture the results?

**Comment by abelinsky** [comment]
Yes, it's possible to set 'output_file' option to see the results of the checker in this text file. Thanks a lot)
