### ISSUE TITLE
Installing cyipopt with the HSL solvers using conda

### ISSUE THREAD

**Issue by takafusui** [mechmotum/cyipopt#133]
Dear all,

Is it possible to install `cyipopt` with the HSL solver using conda?
I succeeded to install `cyipopt` with the HSL support compiling with `setup.py,` but I wonder whether it is possible with the conda package management system.

Thank you very much in advance.

**Comment by moorepants** [comment]
I've added instructions for doing this in PR #138. Can you see if that works for you?

**Comment by kwmcbride** [comment]
I wanted to add that this line was all I needed to get HSL libraries working with cyipopt installed in a conda environment using Mac OS:

```
problem.add_option('hsllib', 'libcoinhsl.dylib')
```

I had already compiled the HSL libraries elsewhere. I was not aware of this option, but it would have saved me hours of trying everything else.
