### ISSUE TITLE
Add CI testing using latest COIN-OR binaries for Windows

### ISSUE THREAD

**Issue by brocksam** [mechmotum/cyipopt#140]
PR #139 addressed #113 (Appveyor no longer running). CI testing on Windows with conda-forge Ipopt for all supported Python versions was translated across to GitHub Actions, but testing with the latest COIN-OR Windows binaries was not. This should be added back to GitHub Actions.

**Comment by moorepants** [comment]
There are two windows binaries on the ipopt github releases:

- https://github.com/coin-or/Ipopt/releases/download/releases%2F3.14.12/Ipopt-3.14.12-win64-msvs2019-md.zip
- https://github.com/coin-or/Ipopt/releases/download/releases%2F3.14.12/Ipopt-3.14.12-win64-msvs2019-mdd.zip

**Comment by moorepants** [comment]
Added in #220.
