### ISSUE TITLE
IPOPT default options

### ISSUE THREAD

**Issue by cmower** [mechmotum/cyipopt#141]
I have a quick query. Have you changed any of the default ipopt options than those specified in [the ipopt documentation](https://coin-or.github.io/Ipopt/OPTIONS.html)? If so, could you please let me know what has been changed?

I am seeing some unexpected convergence issues. It's possible that there is another reason for my problem but I wanted to check with you and make sure this was not the issue.

**Comment by brocksam** [comment]
Are you using the `cyipopt.Problem` class or the Scipy-like interface (`cyipopt.minimize_ipopt`)? For the former, I don't think we do. For the latter, see here: https://github.com/mechmotum/cyipopt/blob/89401cf28345dd59137b272b95f13f0a6d481886/cyipopt/scipy_interface.py#L292-L302.

**Comment by cmower** [comment]
I'm using the `cyipopt.Problem` class. I managed to solve my main issue (no convergence, this was certainly due to me not passing the correct data via gradient/jacobian/hessian function). However, whilst the local minima I find is close to what I expect it's far enough away to make me suspect some of the ipopt options are different - not really an issue for me though. 

Thanks for your time! Great package by the way!

**Comment by brocksam** [comment]
I'm (almost) certain that the only option that gets set in the `cyipopt.Problem` class is to use the limited-memory Hessian if no Hessian is supplied by the user. Other than that, there should not be any difference between CyIpopt and using Ipopt directly via one of its official APIs. If you suspect that you're getting a different answer using CyIpopt than you would using Ipopt directly from C++, please provide additional details and a minimal reproducer.
