### ISSUE TITLE
running a cyipopt instance on a GPU thread

### ISSUE THREAD

**Issue by path-doc** [mechmotum/cyipopt#142]
Hi folks,

we are looking to run a nonlinear optimisation at different points on a large grid. We want to run the optimisation in parallel on a gpu. As a canonical example, for each gridpoint in the nonlinear optimization problem, we would run a thread in the gpu that solves the problem. We have a working model for the cpu. One obstacle we face is how to create the cyipopt.problem class on the gpu so that we can call functions locally (on the gpu). The advice seems to be to simply alter the class so that its methods have the "device" keyword. Eg., with numba.cuda,

```
@cuda.jit(device=True)
def foo():
    return bar
```

Should we do this for the cyipopt.Problem class, or is there a better work around that someone has already come up with?

**Comment by moorepants** [comment]
This seems like a question more for developers of the `@cuda.jit(device=True)` decorator or maybe the IPOPT developers. I'm personally not aware of how one might utilize a GPU with IPOPT/cyipopt.

**Comment by path-doc** [comment]
Okay, thanks for the quick reply. Must admit, I'm surprised I'm the first to ask about this. 

Can you please tell me whether cyipopt is a wrapper for the C++ interface or the C interface?

**Comment by path-doc** [comment]
Just to be clear, I am not looking to parallelise any given NLP, but rather parallelise a family of NLPs. There is a discussion of the former challenge here, but that is not what I wish to do.
https://scicomp.stackexchange.com/questions/20942/is-there-a-constrained-nonlinear-optimization-library-like-ipopt-that-runs-on-gp

**Comment by moorepants** [comment]
> Can you please tell me whether cyipopt is a wrapper for the C++ interface or the C interface?

It is a wrapper to the C interface.

**Comment by moorepants** [comment]
I browsed the stackexchange discussion. Seems like you are searching for solutions that are still nascent. My hunch is that utilizing the GPU in or with interior point solver needs to start a much lower level than cyipopt.

**Comment by path-doc** [comment]
Thanks very much.

**Comment by moorepants** [comment]
Closing this. Please reopen if there is new info or questions in the future.
