### ISSUE TITLE
your jax example doesn't work (even when unjitted)

### ISSUE THREAD

**Issue by path-doc** [mechmotum/cyipopt#147]
I have a version of the Algorithmic Differentiation example that you provide on your [usage page](https://cyipopt.readthedocs.io/en/stable/tutorial.html).

[Here is my version on Colab](https://colab.research.google.com/drive/1_oeiVVFfpDPhri4MZRhb2bYMRxegEH5k?usp=sharing)

In the above, I have stripped out the jit functions. Just to see if I can use jax any way.

The error I always get is:

> TypeError: eq_constraints() takes 1 positional argument but 2 were given

The same goes for the unedited code from your [usage page](https://cyipopt.readthedocs.io/en/stable/tutorial.html):

```python
import numpy as np
import jax.numpy as jnp
from jax import jit, grad, jacfwd, jacrev
from cyipopt import minimize_ipopt
    
def objective(x):
    return x[0]*x[3]*np.sum(x[:3]) + x[2]
def eq_constraints(x):
    return np.sum(x**2) - 40

def ineq_constrains(x):
    return np.prod(x) - 25

# jit the functions
obj_jit = jit(objective)
con_eq_jit = jit(eq_constraints)
con_ineq_jit = jit(ineq_constrains)

# build the derivatives and jit them
obj_grad = jit(grad(obj_jit))  # objective gradient
obj_hess = jit(jacrev(jacfwd(obj_jit))) # objective hessian
con_eq_jac = jit(jacfwd(con_eq_jit))  # jacobian
con_ineq_jac = jit(jacfwd(con_ineq_jit))  # jacobian
con_eq_hess = jacrev(jacfwd(con_eq_jit)) # hessian

con_eq_hessvp = jit(lambda x, v: con_eq_hess(x) * v[0]) # hessian vector-product
con_ineq_hess = jacrev(jacfwd(con_ineq_jit))  # hessian
con_ineq_hessvp = jit(lambda x, v: con_ineq_hess(x) * v[0]) # hessian vector-product

# constraints
cons = [{'type': 'eq', 'fun': con_eq_jit, 'jac': con_eq_jac, 'hess': con_eq_hess},
    {'type': 'ineq', 'fun': con_ineq_jit, 'jac': con_ineq_jac, 'hess': con_ineq_hess}]

# starting point
x0 = np.array([1, 5, 5, 1])

# variable bounds: 1 <= x[i] <= 5
bnds = [(1, 5) for _ in range(x0.size)]

# executing the solver
res = minimize_ipopt(obj_jit, jac=obj_grad, hess=obj_hess, x0=x0, bounds=bnds,
                  constraints=cons, options={'disp': 5})
```

**Comment by moorepants** [comment]
Also, are #145 and #144 the same or related?

**Comment by path-doc** [comment]
The code provided in the following comment works on Colab:

https://github.com/mechmotum/cyipopt/issues/144#issuecomment-1028908026

**Comment by path-doc** [comment]
And the code from https://github.com/mechmotum/cyipopt/issues/144#issuecomment-1028908026 also works on my mac.

Many thanks for the quick responses :)
