### ISSUE TITLE
Warm-starting dual variables

### ISSUE THREAD

**Issue by EpicDuckPotato** [mechmotum/cyipopt#151]
Is there a way to supply an initial guess for the dual variables?

**Comment by EpicDuckPotato** [comment]
Looking at the source code, I found out there are keyword arguments for this (lagrange, zl, and zu for the solve function): https://github.com/mechmotum/cyipopt/blob/master/cyipopt/cython/ipopt_wrapper.pyx. Would be helpful if those were in the documentation.

**Comment by moorepants** [comment]
It does look like a description of the three kwargs is missing here: 

https://github.com/mechmotum/cyipopt/blob/master/cyipopt/cython/ipopt_wrapper.pyx#L574

**Comment by moorepants** [comment]
Closing in favor of #266 which details the specific issue more thoroughly.
