### ISSUE TITLE
KeyError when using IPOPT option "max_wall_time" in minimize_ipopt()

### ISSUE THREAD

**Issue by Osburg** [mechmotum/cyipopt#152]
Hi everyone :)

when I limit the wallclock time with the "max_wall_time" option using `minimize_ipopt()` I get the following KeyError in
`File "cyipopt\cython\ipopt_wrapper.pyx", line 652, in ipopt_wrapper.Problem.solve KeyError: -5`.
This error does not occur when I limit some other quantity like cpu time or number of iterations.

**Comment by moorepants** [comment]
Same as https://github.com/mechmotum/cyipopt/issues/131 and this seems fixed.
