### ISSUE TITLE
How to add multiple constraints in hs071_scipy_jax.py?

### ISSUE THREAD

**Issue by BaymaxArnO** [mechmotum/cyipopt#154]
I want to add some constrains in follow functions:
```
def eq_constraints(x):
    eq1 = x[0]**2 + x[1]**2 - 40
    eq2 = x[2]**2 + x[3]**2 - 40
    eq3 = x[0] + x[3] - 10
    return np.asarray([eq1,eq2,eq3])

def ineq_constrains(x):
    ineq1 = np.prod(x) - 25
    ineq2 = 12 - (x[0] + x[3])
    return np.asarray([ineq1,ineq2])
```
Then I got :
**The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/baitian5/baitian5/cyipopt/examples/hs071_scipy_jax.py", line 72, in <module>
    constraints=cons, options={'disp': 5})
  File "/home/baitian5/baitian5/cyipopt/cyipopt/scipy_interface.py", line 310, in minimize_ipopt
    x, info = nlp.solve(_x0)
  File "cyipopt/cython/ipopt_wrapper.pyx", line 642, in ipopt_wrapper.Problem.solve
  File "cyipopt/cython/ipopt_wrapper.pyx", line 895, in ipopt_wrapper.hessian_cb
  File "/home/baitian5/baitian5/cyipopt/cyipopt/scipy_interface.py", line 165, in hessian
    H += hessian(x, lagr, *args)
  File "/home/baitian5/anaconda3/envs/PR_ENV_LINUX/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 4557, in deferring_binary_op
    return binary_op(self, other)
  File "/home/baitian5/anaconda3/envs/PR_ENV_LINUX/lib/python3.7/site-packages/jax/_src/numpy/ufuncs.py", line 87, in fn
    return lax_fn(x1, x2) if x1.dtype != np.bool_ else bool_lax_fn(x1, x2)
TypeError: add got incompatible shapes for broadcasting: (3, 4, 4), (2, 4, 4). **
How can I solve this?

**Comment by ksb1871** [comment]
Did you manage to find a solution to this? I too am struggling with the same issue

**Comment by jhelgert** [comment]
@BaymaxArnO @ksb1871 You guys only need to change the functions `con_eq_hessvp` and `con_ineq_hessvp` that calculate the hessian-vector-products. For instance,

``` python
con_eq_hessvp = jit(lambda x, v: con_eq_hess(x) * v[0]) # hessian vector-product
```

assumes that we only have one equality constraint, i.e. `con_eq_hess(x)` returns a np.ndarray with shape (1, N, N) where N is the number of variables. In case you have M equality constraints, `con_eq_hess(x)` will return a np.ndarray with shape (M, N, N). Thus, you guys need to calculate `con_eq_hess(x)[0, :, :] * v[0] + ... + con_eq_hess(x)[M-1, :, :] * v[M-1]`. 

In code:

``` python
from jax.config import config

# Enable 64 bit floating point precision
config.update("jax_enable_x64", True)

# We use the CPU instead of GPU und mute all warnings if no GPU/TPU is found.
config.update('jax_platform_name', 'cpu')

from cyipopt import minimize_ipopt
from jax import jit, grad, jacrev, jacfwd
import jax.numpy as np

def eq_constraints(x):
    eq1 = x[0]**2 + x[1]**2 - 40
    eq2 = x[2]**2 + x[3]**2 - 40
    eq3 = x[0] + x[3] - 10
    return np.asarray([eq1,eq2,eq3])

con_eq_jit = jit(eq_constraints)
con_eq_jac = jit(jacfwd(con_eq_jit))  # jacobian
con_eq_hess = jacrev(jacfwd(con_eq_jit)) # hessian
con_eq_hessvp = jit(lambda x, v: np.sum(con_eq_hess(x) * v[:, None, None], axis=0)) # hessian vector-product
```

**Comment by BaymaxArnO** [comment]
邮件已经收到啦，我会尽快回复~~

**Comment by BaymaxArnO** [comment]
邮件已经收到啦，我会尽快回复~~

**Comment by moorepants** [comment]
This seems resolved.

**Comment by BaymaxArnO** [comment]
邮件已经收到啦，我会尽快回复~~
