### ISSUE TITLE
How to use hsl with casadi in my environment?

### ISSUE THREAD

**Issue by Devil-li-x** [mechmotum/cyipopt#155]
I downloaded ubantu 22.04 on the official website of ubantu and installed it in the virtual machine. Then I downloaded the anaconda 3 environment in the system and created the environment of Python 37 in the env folder. In the environment of Python 37, PIP install casadi. Then I completed the compilation of HSL and generated the include and Lib folders according to the operation of thirdparty. However, when I ran my code here, I still prompted that Ma 57 was an invalid option.
Please help me.

**Comment by moorepants** [comment]
If you are using anaconda, I recommend installing everything with conda (including ipopt and casadi). If you need HSL solvers, this explains how to compile against the ipopt installed with conda: https://cyipopt.readthedocs.io/en/latest/install.html#conda-forge-binaries-with-hsl

**Comment by Devil-li-x** [comment]
@moorepants  The kit I use is mpctools, built on top of casadi, and after I install ipopt, mpctools  may not be recognized

**Comment by moorepants** [comment]
I would suggest asking for help about other tools in their discussion channels. This issue tracker is for cyipopt and we have given a recommended method for installing HSL with cyipopt on ubuntu. I'm going to close this issue, as it seems unrelated to cyipopt. Good luck!
