### ISSUE TITLE
New Tagged Version

### ISSUE THREAD

**Issue by daugihao** [mechmotum/cyipopt#158]
Doing some maintenance of our company's codebase and we are currently seeing the scipy namespace warning that is fixed in https://github.com/mechmotum/cyipopt/pull/157. We've noticed that there's not been a new tag for a while so we don't feel safe to upgrade - is that something which is imminent?

Many thanks!

**Comment by brocksam** [comment]
#157 is really the only change that's occurred since the 1.1.0 release, but since that was more than a year ago another is probably justified. @moorepants: what do you think about a 1.1.1 (or even 1.2.0) release so that pip and conda users see #157? I'm happy to initiate with your approval.

**Comment by daugihao** [comment]
That would be fabulous if you were happy to do so 🙏

**Comment by moorepants** [comment]
Yes, we can release.

**Comment by moorepants** [comment]
I opened #159.

**Comment by moorepants** [comment]
cyipopt 1.2.0 is now on pypi.

**Comment by moorepants** [comment]
conda forge version is out too
