### ISSUE TITLE
Ipopt finds a better solution if I do not eliminate the zeros in the hessian matrix ?(we eliminate the zeros by defining the structure)

### ISSUE THREAD

**Issue by hssharadga** [mechmotum/cyipopt#172]
I use Ipopt to solve a problem with sparse hessian and jacobian matrices.

If I provide the hessian matrix: its structure, and the nonzeros elements in the hessian matrix, it will be really fast.

If I do not define the hessian structure but provide the whole hessian matrix, which is almost zeros, the solver will be slow but converge to a better solution!

Does that mean the zeros help the solver find a better solution?

**Comment by moorepants** [comment]
This sounds like a question you should be asking the IPOPT support channels about. Please ask your question over there.

**Comment by hssharadga** [comment]
Thank you, Jason.

If I may ask, where can I find the  IPOPT support channels?

Thanks a lot,
Hussein

**Comment by moorepants** [comment]
I don't know, there used to be a mailing list. I recommend searching for the main IPOPT website.
