### ISSUE TITLE
Multiple GitHub Actions failures due to `conda-incubator/setup-miniconda@v2`

### ISSUE THREAD

**Issue by brocksam** [mechmotum/cyipopt#177]
Multiple GitHub Actions jobs are failing during the `Setup conda-incubator/setup-miniconda@v2` step, with the error:

```bash
Error: The process '/usr/share/miniconda/condabin/conda' failed with exit code 1
```

**Comment by brocksam** [comment]
Appears to only affect Windows and Ubuntu, macOS jobs are still succeeding.

**Comment by brocksam** [comment]
Issue now open at https://github.com/conda-incubator/setup-miniconda/issues/274.

**Comment by moorepants** [comment]
I guess we should try the mambaforge solution? Looks like dozens of people are implementing a workaround in the issue.
