### ISSUE TITLE
Optimization variables in callback function

### ISSUE THREAD

**Issue by DanielLichtenecker** [mechmotum/cyipopt#180]
Hi,

is there any way to access the current optimization variables in the callback function intermediate?

```
 def intermediate(self, alg_mod, iter_count, obj_value, inf_pr, inf_du, mu,
                     d_norm, regularization_size, alpha_du, alpha_pr,
                     ls_trials):
```

 I would like to plot a graph including these variables during the optimization for debugging.   

Thanks for your help!

**Comment by brocksam** [comment]
Having just looked at [the source code](https://github.com/mechmotum/cyipopt/blob/d2ecd731c64de09928c5744073a2606404d87dac/cyipopt/cython/ipopt_wrapper.pyx#L908-L948) it doesn't look like it currently is possible, which does surprise me. If we're correct, I'm unsure whether this is a limitation of CyIpopt's wrapper or the Ipopt C API. If it's the former then a PR could allow this to be supported. If it's the latter then it wouldn't be possible without a contribution to Ipopt first.

**Comment by DanielLichtenecker** [comment]
Can you clarify if this is a limitation of the wrapper or the Ipopt API?

**Comment by brocksam** [comment]
It looks like the CyIpopt API exactly matches the Ipopt C API, which we wrap. [See here](https://coin-or.github.io/Ipopt/IpStdCInterface_8h.html). So I don't think adding support for this via CyIpopt would be possible without first changing Ipopt's C interface.

**Comment by brocksam** [comment]
> Ok, but through the pointer user_data in the Intermediate_CB method ([see](https://coin-or.github.io/Ipopt/IpStdCInterface_8h.html#a0a2bc6b1dc188466a5eed53a50dd15df)) it should be possible to access the optimization variables or?

I don't know what `UserDataPtr` points to.

> This [function](https://coin-or.github.io/Ipopt/IpStdCInterface_8h.html#acf68350650b7a893061e110ab0e9264f) also sounds promising to get the primal variables in each iteration.

I agree, it does look promising. However, I believe we don't currently have it wrapped. A PR adding a wrapper for it to the CyIpopt API would be welcomed if you're willing and able to contribute that?

**Comment by brocksam** [comment]
It may also be worth waiting until someone else chimes in on this issues as I may well just be blissfully unaware of how to do what you've asked with CyIpopt in its current state.

**Comment by Robbybp** [comment]
I think we have what we need to implement this, the question is mostly just about how to return the information to the user, especially given that this functionality did not exist pre-Ipopt 3.14. Unfortunately I'm not very familiar with Cython, but I think what we need is something like:

1. Define `GetIpoptCurrentIterate` and `GetIpoptCurrentViolations` in `ipopt.pxd`:
```cython
Bool GetIpoptCurrentIterate(
                IpoptProblem ipopt_problem,
                Bool scaled,
                Index n,
                Number* x,
                Number* z_L,
                Number* z_U,
                Index m,
                Number* g,
                Number* lambd
                )

Bool GetIpoptCurrentViolations(
                IpoptProblem ipopt_problem,
                Bool scaled,
                Index n,
                Number* x_L_violation,
                Number* x_U_violation,
                Number* compl_x_L,
                Number* compl_x_U,
                Number* grad_lag_x,
                Index m,
                Number* nlp_constraint_violation,
                Number* compl_g
                )
```
Somewhere along the line we probably also need to declare IpoptProblemInfo:
```cython
cdef struct IpoptProblemInfo:
    # These are SmartPtrs to IpoptApplication and StdInterfaceTNLP.
    # Unclear if we can get away with void *, or if they need to be included at all
    void *app
    void *tnlp
    Index n
    Number *x_L
    Number *x_U
    Index m
    Number *g_L
    Number *g_U
    Index nele_jac
    Index nele_hess
    Index index_style
    Eval_F_CB eval_f
    Eval_G_CB eval_g
    Eval_Grad_F_CB eval_grad_f
    Eval_Jac_G_CB eval_jac_g
    Eval_H_CB eval_h
    Intermediate_CB intermediate_cb
    Number obj_scaling
    Number *x_scaling
    Number *g_scaling
```
2. Access the IpoptProblem in `intermediate_cb` in `ipopt_wrapper.pyx` to send to these functions:
```cython
cdef Bool intermediate_cb(Index alg_mod,
                          Index iter_count,
                          Number obj_value,
                          Number inf_pr,
                          Number inf_du,
                          Number mu,
                          Number d_norm,
                          Number regularization_size,
                          Number alpha_du,
                          Number alpha_pr,
                          Index ls_trials,
                          UserDataPtr user_data
                          ):

    log(b"intermediate_cb", logging.INFO)

    cdef object self = <object>user_data

    problem = <Problem>user_data
    n = problem.__nlp.n
    x = np.zeros(n, dtype=DTYPEd)
    z_L = np.zeros(n, dtype=DTYPEd)
    z_U = np.zeros(n, dtype=DTYPEd)
    m = problem.__nlp.m
    g = np.zeros(m, dtype=DTYPEd)
    lambd = np.zeros(m, dtype=DTYPEd)
    ret = GetIpoptCurrentIterate(problem.__nlp,
                                 False,
                                 n,
                                 x,
                                 z_L,
                                 z_U,
                                 m,
                                 g,
                                 lambd
                                 )
    # Do something with the iterate now stored in x, z_L, z_U, g, and lambd
    # Presumably we would like to return it to the user, somehow.

    if self.__exception:
        return False

    if not self.__intermediate:
        return True 

    ret_val = self.__intermediate(alg_mod,
                                  iter_count,
                                  obj_value,
                                  inf_pr,
                                  inf_du,
                                  mu,
                                  d_norm,
                                  regularization_size,
                                  alpha_du,
                                  alpha_pr,
                                  ls_trials
                                  )
```
As may be clear from the above code, I really don't know cython. But hopefully we can find a way to implement this functionality, as returning full iterate vectors (as well as violations) would be amazingly useful.

**Comment by moorepants** [comment]
If you make a pull request and we see what fails, we can help you iterate through it.

**Comment by Robbybp** [comment]
I can try to find some time for this in the next week or so.
