### ISSUE TITLE
FunctionWithApproxJacobian is not defined when calling ipopt_minimize

### ISSUE THREAD

**Issue by kktse** [mechmotum/cyipopt#19]
`ipopt_minimize` will raise an exception when called `NameError: name 'FunctionWithApproxJacobian' is not defined`

It appears there is divergence between the [Optpy](https://github.com/matthias-k/optpy/blob/master/optpy/ipopt_wrapper.py) project and [cyipopt](https://github.com/matthias-k/cyipopt/blob/master/ipopt/ipopt_wrapper.py), with the implementation here ported for Python3 compatibility. However, its missing the related file `jacobian.py` so the wrapper just doesn't work.

I'm trying to (naively) replace a `scipy.optimize.minimize` calls with IPOPT. Figure it should be a working feature since its at the beginning of the README.

The solution doesn't look too bad. May need to merge some changes between Optpy and here, and include a Python2/3 compatible version of `jacobian.py`.

**Comment by moorepants** [comment]
Please provide a minimal example that demonstrates the undesired behavior.

**Comment by nie93** [comment]
The code block in the `README.md` file also confuses me. The usage looks like `scipy.optimize.minimize()` and constraints are added by setting up a `constraints` option, but I think the proper usage of `ipopt` module should be like [/test/examplehs071.py](https://github.com/matthias-k/cyipopt/blob/master/test/examplehs071.py).

The following code is an example causes the same error:
```sh
NameError: global name 'FunctionWithApproxJacobian' is not defined
```

```py
from scipy.optimize import minimize, rosen, rosen_der
from ipopt import minimize_ipopt

fun = lambda x: (x[0] - 1)**2 + (x[1] - 2.5)**2
cons = ({'type': 'ineq', 'fun': lambda x:  x[0] - 2 * x[1] + 2},
        {'type': 'ineq', 'fun': lambda x: -x[0] - 2 * x[1] + 6},
        {'type': 'ineq', 'fun': lambda x: -x[0] + 2 * x[1] + 2})
bnds = ((0, None), (0, None))

x0 = [1.3, 0.7, 0.8, 1.9, 1.2]
res = minimize_ipopt(rosen, x0, jac=rosen_der, bounds=bnds, constraints=cons)

print(res.x)
```

**Comment by perak96** [comment]
Hello,

Did anyone come up with a solution to this problem?
Thnaks

**Comment by moorepants** [comment]
No one has submitted a pull request regarding this as far as I am aware. We will happily take contributions.

**Comment by moorepants** [comment]
You can see in the code for cyipopt that `FunctionWithApproxJacobian` is used but never defined or imported.

https://github.com/matthias-k/cyipopt/blob/43cff244e5e7a44e86e446160116c2fdb3836d12/ipopt/ipopt_wrapper.py#L67

Looks like this was defined in a different package:

https://github.com/matthias-k/optpy/blob/master/optpy/jacobian.py

But never added to this package.

**Comment by moorepants** [comment]
If someone would like to port some of the things from https://github.com/matthias-k/optpy to this repository, that is fine. Especially to get the scipy-like functionality working.

**Comment by perak96** [comment]
@moorepants 

Thanks for your help, I just copied everything from https://github.com/matthias-k/optpy/blob/master/optpy/jacobian.py into ipopt_wrapper.py and it seems to be working now.

**Comment by moorepants** [comment]
Feel free to make a pull request with that fix.

**Comment by andr1976** [comment]
Hi @moorepants 
I have a fix, but don't have permissions to push and create a pull request. Can you add me?

**Comment by moorepants** [comment]
To create a pull request you need to fork the repository make your changes on your fork in a new branch and then make a pull request. Anyone can do this with a github account.

**Comment by andr1976** [comment]
Thanks

**Comment by moorepants** [comment]
Anyone can do this with a github account should have said "If you have a github account you have the permissions to do this." Here is an explanation if needed: https://opensource.com/article/19/7/create-pull-request-github
