### ISSUE TITLE
conda package cyipopt for osx-arm64

### ISSUE THREAD

**Issue by pollinico** [mechmotum/cyipopt#190]
Hi, 

I cannot install with conda install -c conda-forge cyipopt.

I have a mac os with M1 chip. I run miniconda for osx-arm64 architecture. Is there a package for this architecture?

Do you have tips in case?

Thank you!

**Comment by moorepants** [comment]
This request belongs on the conda forge feedstock repo: https://github.com/conda-forge/cyipopt-feedstock
