### ISSUE TITLE
Linear solver setttings

### ISSUE THREAD

**Issue by rlacjfjin** [mechmotum/cyipopt#193]
Hi,
 is it possible to setting linear solver? such as:

-----------
linear_solvers = ["mumps", "ma27", "ma57","ma77","ma86","ma97","pardiso","pardisomkl","spral","wsmp"]
for linear_solver in linear_solvers:
     nlp.add_option("linear_solver", linear_solver)

-----------

I install cyiopt using conda install and in my enviroment it is only success mumps linear solver.
How can I use other solvers?(windows)

Thanks.
Zhe

**Comment by moorepants** [comment]
If you want to use alternative linear solvers you will have to install them yourself. We can't ship many of the solvers with ipopt on conda-forge because the solvers are proprietary.
