### ISSUE TITLE
save the model

### ISSUE THREAD

**Issue by rlacjfjin** [mechmotum/cyipopt#198]
Hi,

Is it possible to save the model in cyipopt? Such as pyomo using lp or mps format(maybe other format in nlp).
Or can cyipopt read problem from a file? 

And another question:
I find it can calculate hessian matrix numerically, and why it can't calculate jacobian matrix? If I only refer the obejctive function and constraints with bounds, is it can solve the problem? 

Thanks.
Zhe

**Comment by moorepants** [comment]
Hi,

I think your questions are best for pyomo, we don't know anything about pyomo here.

Your numerical calculation questions are probably best for ipopt. ipopt can calculate derivatives numerically, you'll have to see how to do that in the ipopt documentation. cyipopt is a wrapper to ipopt's c interface and we do our best to support what is available there.

**Comment by rlacjfjin** [comment]
Thanks,
I set:
    nlp.add_option("gradient_approximation","finite-difference-values")
    nlp.add_option("jacobian_approximation","finite-difference-values")
it can work well.
And this helped me a lot, thanks for your reply.

Zhe
