### ISSUE TITLE
Expose docstrings of  get_current_iterate and get_current_violations

### ISSUE THREAD

**Issue by moorepants** [mechmotum/cyipopt#202]
Looks like we need to add some sphinx autodoc statements for these to show up here:

https://cyipopt.readthedocs.io/en/latest/reference.html

**Comment by Robbybp** [comment]
Has this been fixed? I see the docstrings on this doc page:
![Screenshot from 2023-06-06 14-25-39](https://github.com/mechmotum/cyipopt/assets/8885032/49fc6be2-de94-4b83-87a8-317de73df269)

If there is something missing, I would be happy to add.

**Comment by moorepants** [comment]
Yes, I see them.
