### ISSUE TITLE
installation problem dll load failed while importing ipopt_wrapper

### ISSUE THREAD

**Issue by AlexandreMoulti** [mechmotum/cyipopt#209]
Hi,

I have issues while installing cyipopt.
I have the last anaconda installed and need to install from files (proxy blocking) that I download from conda website
Here is the message

-------------

(base) C:\Users\Alexandre>python
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

(base) C:\Users\Alexandre>conda install C:\Users\Alexandre\Downloads\cyipopt-1.2.0-py310h3c1d9b9_2.conda
Retrieving notices: ...working... done

Downloading and Extracting Packages

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) C:\Users\Alexandre>python
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cyipopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Temp\Anaconda\lib\site-packages\cyipopt\__init__.py", line 12, in <module>
    from ipopt_wrapper import *
ImportError: DLL load failed while importing ipopt_wrapper: Le module spécifié est introuvable.

**Comment by moorepants** [comment]
Have you installed all the dependencies?

**Comment by AlexandreMoulti** [comment]
I have all the requirements except ipopt
I thought this package installs a wrapper around ipopt + ipot itself
My understanding comes from the documentation that I followed and got this :

 C:\Users\Alexandre\Downloads\cyipopt-master\cyipopt-master>conda install -c conda-forge cyipopt
Collecting package metadata (current_repodata.json): done
Solving environment: -
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - <unknown>/win-64::cyipopt==1.2.0=py310h3c1d9b9_2

**Comment by moorepants** [comment]
> I have all the requirements except ipopt

Ipopt is a requirement that needs to be installed.

>  I thought this package installs a wrapper around ipopt + ipot itself

It does not install ipopt, you should install the ipopt conda forge binary.

**Comment by AlexandreMoulti** [comment]
Indeed it works by creating an environment, thanks
however on my professional pc I am behind a proxy and cannot execute the conda environment creation
do you know how to proceed?

**Comment by moorepants** [comment]
I think that is a question for the conda forum.

**Comment by moorepants** [comment]
Like I said, this is a question for conda people. I am no familiar with this.

Ask here: https://conda.discourse.group/

**Comment by moorepants** [comment]
I'm going to close this issue, as it is out of scope now.
