### ISSUE TITLE
Maintenance status of cyipopt

### ISSUE THREAD

**Issue by chrhansk** [mechmotum/cyipopt#218]
I am using cyipopt quite regularly in my own projects and I am a little worried regarding its maintenance status:

- Several pull requests have been made with no signs of them being merged
- Issues are similarly not being addressed, even if they are fairly critical (#217, #211)
- It is unclear who feels responsible for any maintenance, @moorepants sometimes comments, but does not seem to take actions (?)

Please understand that I do not want to criticize the volunteers who made this package available. I would just like to avoid the situation of a package I am using a lot becoming stale and difficult or impossible to use. Do you need any help with maintaining the package (I would be happy to step in)?

**Comment by moorepants** [comment]
I and others maintain the package. If it is too slow for you, you are welcome to help. I am happy to give commit rights to people that have made significant contributions to the package and follow our development practices.

I don't see anything that is critical, as you mention. I will happily accept a pull request to update for building with Cython 3, but for now you can simply pin to less than 3 when building.

`pip install` will not work until someone distributes wheels of ipopt that we can link against. You have to follow the build instructions in the documentation to install cyipopt.

**Comment by chrhansk** [comment]
Well, I must admit that I am trying to scratch my own itch. `pip install` does not work on my Linux system either, though this seems to have been fixed in the current version, so having a release with the current state and the fix for my pet peeves (https://github.com/mechmotum/cyipopt/pull/216) merged would go a long way in my opinion.

As for the maintenance, I get that we work on projects in our off-time, so I of course don't expect any customer service here. I also understand that in this case you do not want to bestow commit access to people who have not contributed much yet. On the other hand, contributing seems a little difficult for me if I get no feedback on my pull requests (if you think I made a mistake or if other improvements are needed, please tell me so).

**Comment by moorepants** [comment]
> pip install does not work on my Linux system either

Cython (a build dependency) will likely have to be pinned <3 if you are installing the last release. If it isn't that, then please open an issue about it.

> contributing seems a little difficult for me if I get no feedback on my pull requests

You submitted a PR in late July. The month of August is holidays where I live and I'm busy with the start of the school year in my job in September, so please be patient. Some things take months.

> so having a release with the current state

I hope to make a new release by the end of the year.

I'm closing this issue, please reopen if it isn't addressed.

**Comment by chrhansk** [comment]
Thanks for the consideration, hope you had nice holidays.
