### ISSUE TITLE
ENH: support `keep_feasible=True` like `scipy.optimize.minimize` with `method='trust-constr'`?

### ISSUE THREAD

**Issue by mdhaber** [mechmotum/cyipopt#231]
`cyipopt.minimize_ipopt` now supports the definition of constraints with [`Bounds`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.Bounds.html#scipy.optimize.Bounds), [`LinearConstraint`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.LinearConstraint.html#scipy.optimize.LinearConstraint), and [`NonlinearConstraint`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.NonlinearConstraint.html#scipy.optimize.NonlinearConstraint) objects like `scipy.optimize.minimize`. Unlike `scipy.optimize.minimize` with `method='trust-constr'`, however, the `keep_feasible` option:

![image](https://github.com/mechmotum/cyipopt/assets/6570539/b4748cf0-5fbc-4a44-a9ed-b3992e29c9e5)

of these constraints is ignored. 
Does Ipopt have any way to ensure that (inequality) constraints are never violated (as long as the guess is feasible)?
If not, this issue can be closed, IMO. If so, however, this is an enhancement request for `minimize_ipopt` to respect `keep_feasible`.

**Comment by Robbybp** [comment]
I don't believe Ipopt has a way to ensure that inequality constraints are never violated

**Comment by mdhaber** [comment]
I couldn't find one either, so closing.
