### ISSUE TITLE
`print_level` doesn't seem to work correctly for `minimize_ipopt`

### ISSUE THREAD

**Issue by AlexanderThebeltQC** [mechmotum/cyipopt#234]
When I give `options = {"disp": 5}` to `minimize_ipopt` it always ends up using `{b"print_level": 0}`, meaning no output is printed. I believe the problem is [here in the code](https://github.com/mechmotum/cyipopt/blob/d00088053569a6486510ed8c2baafb38ad3eb6a2/cyipopt/scipy_interface.py#L585C1-L588C36). Given that `options` is a `dict` it will always end up in the `else` case. Maybe `option.get()` is more suitable here? And it would be great if we can allow for display levels greater than `1`. Apologies if I'm missing something or using the interface wrong!

**Comment by Robbybp** [comment]
This looks like a bug to me, and your proposed fix sounds good. I see no reason not to allow `print_level > 1` in the SciPy interface. PRs welcome!

**Comment by MarkusZimmerDLR** [comment]
The linked PR is not making any progress and is mixing issues which are not related.

I suggest creating a simple hotfix for this, changing

```python
if getattr(options, 'print_level', False) is True:
    options[b'print_level'] = 1
```

to 
```python
options[b'print_level'] = int(getattr(options, b'print_level', 5) )
```
