### ISSUE TITLE
Missing warm start kwarg explanations in the docstring of solve()

### ISSUE THREAD

**Issue by Peter230655** [mechmotum/cyipopt#266]
In this reference:
: https://cyipopt.readthedocs.io/en/latest/reference.html#cyipopt.Problem.solve
the method solve is given like this:
![image](https://github.com/user-attachments/assets/f7fd0952-3ef2-4506-85d8-24968d66d8b9)

The term **x** is clearly explained, but lagrange=[], zl=[], zu=[] are not explained or mentioned.
I also did not find anything in the tutorial referred to.
_Would it make sense to add some explanation?_

Thanks!

**Comment by moorepants** [comment]
The `lagrange`, `zl`, and `zu` are used to warm start a solve. These values are passed into `IpoptSolve()` for `mult_g`, `mult_x_L`, and `mult_x_U` respectively. Those parameters should be documented in the `solve()` docstring and should reflect the documentation in Ipopt.

**Comment by moorepants** [comment]
From Ipopt: https://github.com/coin-or/Ipopt/blob/e10e5c738605f0525a50cbdaa624d56378986c77/src/Interfaces/IpStdCInterface.h#L315

**Comment by Peter230655** [comment]
> The `lagrange`, `zl`, and `zu` are used to warm start a solve. These values are passed into `IpoptSolve()` for `mult_g`, `mult_x_L`, and `mult_x_U` respectively. Those parameters should be documented in the `solve()` docstring and should reflect the documentation in Ipopt.

Just curiosity: what does 'warm start' mean?

**Comment by moorepants** [comment]
It is the Ipopt terminology for providing an initial guess along with all of the internal interior point optimization characterization variables to accelerate the path to the solution. Google "ipopt warm start".

**Comment by moorepants** [comment]
This issue was already pointed out in #151.

**Comment by Peter230655** [comment]
> This issue was already pointed out in #151.

I di not know this.

**Comment by moorepants** [comment]
The kwargs were added in https://github.com/mechmotum/cyipopt/pull/1

**Comment by Peter230655** [comment]
> The kwargs were added in #1

I think, this is way above my head! :-(
I better stick to the simple stuff like chaning a plotting method :-)

**Comment by Peter230655** [comment]
> It is the Ipopt terminology for providing an initial guess along with all of the internal interior point optimization characterization variables to accelerate the path to the solution. Google "ipopt warm start".

I did. Way above my head!
