### ISSUE TITLE
Host documentation with readthedocs or doctr

### ISSUE THREAD

**Issue by moorepants** [mechmotum/cyipopt#36]
PyPi doesn't really host documentation anymore. We should set up readthedocs or doctr if more flexibility is needed.

**Comment by moorepants** [comment]
@matthias-k, can you give me more permissions with this repo? I need them to be able to setup webhooks and such. We could also consider moving the repo to an existing or new organization to help manage multiple repo admins.

**Comment by matthias-k** [comment]
@moorepants Actually, just a few days ago I thought that it might make sense to move this repository to an organization. Maybe at some point I will contribute again, but right now I don't use ipopt at all and don't really have time to contribute. I also checked the repository settings and it doesn't look like I can give you more permissions to setup webhooks and similar things. An organization might be both the most elegant and also the only way to make sure that this repository doesn't depend too much on me :).

**Comment by moorepants** [comment]
Ok, sounds good to me. One option is I can put it in my lab org: https://github.com/mechmotum/ as I plan to use the package and support it with my lab for the foreseeable future or we create a new one. I guess we'd just call the new org "cyipopt" also if we did that as I don't know of any other umbrella term.

**Comment by matthias-k** [comment]
@moorepants both sound good to me. You are the primary maintainer right now, so I think you can decide whatever suits you most. The lab org might be the easiest option for now and would make your lab visible as the main source of contribution. Cool lab, by the way!

**Comment by moorepants** [comment]
Another option would be to see if coin-or wants to engulf it. But, easiest is just to move it to my lab's org.

Glad you like the lab! It's fun!

**Comment by moorepants** [comment]
@matthias-k Can you do the transfer to https://github.com/mechmotum/. I'll then setup a team and give you max permissions I can.

**Comment by matthias-k** [comment]
@moorepants I tried, but I cannot yet do that: "You don’t have the permission to create public repositories on mechmotum". I guess you first have to add me to mechmotum. Then I can transfer the repository to the organization and after that you can remove me from mechmotum again.

**Comment by moorepants** [comment]
Ok, let me see.

**Comment by moorepants** [comment]
Just sent the invite.

**Comment by matthias-k** [comment]
@moorepants thanks, now it worked! The repository belongs to mechmotum now. You can now probably remove me from your lab organization again.

**Comment by moorepants** [comment]
Ok, I'll make you this I think: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/converting-an-organization-member-to-an-outside-collaborator

**Comment by moorepants** [comment]
Actually, I guess you can just a collab on that repo. Is that fine?

**Comment by matthias-k** [comment]
@moorepants I just wanted to suggest that. You have been doing all the maintainer work over the last years anyway. So for me it's perfectly fine if I contribute in the same was as everybody else.

**Comment by moorepants** [comment]
I've tried to give you admin privileges as a collaborator, which is fine with me.

**Comment by matthias-k** [comment]
sounds good!

**Comment by matthias-k** [comment]
but if it turns out to be complicated, I'm sure I can manage without admin rights :).

**Comment by moorepants** [comment]
I think it is setup correctly. Cool! I'm working on the readthedocs integration now.

**Comment by moorepants** [comment]
We have a live readthedocs page!
