### ISSUE TITLE
Update the install instructions and CI for Linux and MacOS for Ipopt >=3.13.0

### ISSUE THREAD

**Issue by apommel** [mechmotum/cyipopt#66]
Even though cyipopt is intrinsically compatible with Ipopt >=3.13.0 on Linux (and likely MacOS), the build instructions are outdated as the Ipopt structure changed. Also, CI is locked on Ipopt <3.13.0 as pkg-config seems to not be configured properly for the latest conda Ipopt.

The new build instructions using coinbrew for Ipopt are detailed on [Ipopt github](https://github.com/coin-or/Ipopt#getting-started) and their [documentation](https://coin-or.github.io/user_introduction#linux-1).
I have written a draft of [.travis.yml](https://github.com/apommel/cyipopt/blob/travis-3.13.2-draft/.travis.yml) that would maybe work with Ipopt 3.13.2 built from source. However, I am not sure if it follows the Linux best practices as I have not much experience on the system. It would also be better to make it work with a conda installed Ipopt.

**Comment by moorepants** [comment]
@richardotis may have done some work on this already.

**Comment by richardotis** [comment]
Our downstream has been making moves in factoring Ipopt out of our dependency chain, so I will not be working any further on this. There are several unmerged PRs at varying stages of completeness, but they were mostly written for Windows, and on the 3.12.x series. Most of the work is on PRs against https://github.com/conda-forge/ipopt-feedstock/pulls?q=author%3Arichardotis but I don't see anything relevant to 3.13.x.

**Comment by richardotis** [comment]
Ah, here we go, forgot that it was someone else who actually got it over the finish line for 3.13: https://github.com/conda-forge/ipopt-feedstock/pull/39

**Comment by moorepants** [comment]
Note that cyipopt 0.2.0 installs fine with ipopt 3.13.2: https://github.com/conda-forge/cyipopt-feedstock/pull/22

**Comment by moorepants** [comment]
@richardotis I thought you'd mentioned to me you had cyipopt patched for new ipopt (or windows) builds. I forget and can't find the note anymore.

**Comment by moorepants** [comment]
I think all of this is addressed and will be in the next release, reopen if not.
