### ISSUE TITLE
How to get number of function evaluation from cyipopt?

### ISSUE THREAD

**Issue by arielBWong** [mechmotum/cyipopt#71]
Is it possible to get the number of function evaluation from solver results?
It is printed in output, but not sure how to retreive it from interface?

**Comment by arielBWong** [comment]
Thank you so much for answering. Sorry that my question was not clear enough. 
In my task,  I need to count the number of objective functions (Number of objective function evaluations ).
As in the following prints (copied your answer content)

Number of objective function evaluations             = 13
Number of objective gradient evaluations             = 13
Number of equality constraint evaluations            = 13
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 13
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 12

I can set option on max iteration count, but could not find an variable for number of objective function/constraint evaluations.

**Comment by brocksam** [comment]
Again, as far as I'm aware this is not possible to do directly through cyipopt, but `itertools` can be used to help put in a workaround.

Try
```
import itertools

class hs071(object):

    def __init__(self):
        self._obj_func_eval_counter = itertools.count()
        self.num_obj_func_evals = next(self._obj_func_eval_counter)

    def objective(self, x):

        # 
        # Your objective function evaluation code setting temporary variable `obj_func_val`
        # 

        self.num_obj_func_evals = next(self._obj_func_eval_counter)

        return obj_func_val

    # Other method definitions (`gradient`, `constraints` etc.) here

x0 = [1.0, 5.0, 5.0, 1.0]

lb = [1.0, 1.0, 1.0, 1.0]
ub = [5.0, 5.0, 5.0, 5.0]

cl = [25.0, 40.0]
cu = [2.0e19, 40.0]

problem_instance = hs071()
nlp = ipopt.problem(
            n=len(x0),
            m=len(cl),
            problem_obj=problem_instance,
            lb=lb,
            ub=ub,
            cl=cl,
            cu=cu
            )

x, info = nlp.solve(x0)

# Extract number of objective function evaluations at IPOPT exit
num_obj_fun_evals = problem_instance.num_obj_func_evals
```

If this is needed for multiple methods (e.g. `gradient`, `constraints`, `jacobian` etc. as well as `objective`) I'd suggest implementing a decorator so that the same approach can be applied in multiple places.

**Comment by moorepants** [comment]
This seems resolved, closing.
