### ISSUE TITLE
Improve error handling when nele_jac is a larger number than Index type supports

### ISSUE THREAD

**Issue by ForceBru** [mechmotum/cyipopt#93]
I would like to have 3 million variables and about half a million constraints (I'm lowkey starting to worry whether this is a bit too many), but I can't even create a problem with 6443 constraints:

```python
Python 3.9.1 (default, Dec 11 2020, 06:28:49) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cyipopt
>>> M = 6443
>>> N = 3000000
>>> dummy_problem_obj = type('Problem', (), {'objective': 1, 'gradient': 1, 'constraints': 1, 'jacobian': 1})
>>> cyipopt.problem(
... n=N, m=M,
... problem_obj=dummy_problem_obj,
... lb=None, ub=None,
... cl=[0]*M, cu=None
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/cyipopt.pyx", line 329, in cyipopt.problem.__init__
ValueError: m > 0 and number of jacobian elements < 1
>>> M -= 1
>>> M
6442 # one less constraint
>>> cyipopt.problem(
... n=N, m=M,
... problem_obj=dummy_problem_obj,
... lb=None, ub=None,
... cl=[0]*M, cu=None
... )
<cyipopt.problem object at 0x107f62dc0>
>>>
```

The error message seems to come from here: https://github.com/mechmotum/cyipopt/blob/5b5e11db4f0f0b93c6d95ec68e6ecb6b394141e3/cyipopt/cython/ipopt_wrapper.pyx#L325-L326

Here `nele_jac` is defined like this: https://github.com/mechmotum/cyipopt/blob/5b5e11db4f0f0b93c6d95ec68e6ecb6b394141e3/cyipopt/cython/ipopt_wrapper.pyx#L302

Clearly, the product of two positive numbers can't be negative! Unless `Index` is a signed type that can't handle the number `6443 * 3000000  == 19'329'000'000`...

The error message is highly misleading: it says "number of jacobian elements < 1", so the user would think that their jacobian has _zero_ elements, since the _number of elements_ is clearly non-negative. But the actual condition it's checking is `nele_jac < 0`, so this error arises specifically when the number of elements _is_ negative which doesn't make any sense from the user's point of view because a number of things can't be negative. Unless there's a weird signed underflow/overflow error.

--------

## Versions

* Python 3.9.1
* cyipopt 0.3.0            py39h4f1db76_1    conda-forge

Since the latest version seems to be 1.0.0: https://github.com/mechmotum/cyipopt/blob/5b5e11db4f0f0b93c6d95ec68e6ecb6b394141e3/cyipopt/version.py#L16

I could simply be using a really old version, but it seems to be the latest one from Anaconda (https://anaconda.org/conda-forge/cyipopt) and PyPI (https://pypi.org/project/ipopt/), so this should still be applicable.

**Comment by bocklund** [comment]
I think you're seeing an overflow for 32 bit integers:


```python
import logging
logging.basicConfig(level='DEBUG')

import cyipopt
M = 6443
N = 3000000
dummy_problem_obj = type('Problem', (), {'objective': 1, 'gradient': 1, 'constraints': 1, 'jacobian': 1})

print(f"M = {M}")
try:
    cyipopt.problem(n=N, m=M, problem_obj=dummy_problem_obj, lb=None, ub=None, cl=[0]*M, cu=None)
except Exception as e:
    print(e)
    pass

M = 6442
print(f"M = {M}")
cyipopt.problem(n=N, m=M, problem_obj=dummy_problem_obj, lb=None, ub=None, cl=[0]*M, cu=None)
```

Running this gives:


```python
M = 6443
INFO:root:b'Hessian callback not given, setting nele_hess to 0'
m > 0 and number of jacobian elements < 1
M = 6442
INFO:root:b'Hessian callback not given, setting nele_hess to 0'
DEBUG:root:b'\n----------------------------------------------------\nCreating Ipopt problem with the following parameters\nn = 3000000\nm = 6442\njacobian elements num = 2146130816\nhessian elements num = 0\n'
INFO:root:b'Hessian callback not given, using approximation'
```

Note that 2,146,130,816 that you see with `M = 6442` is not far from to 2,147,483,647, the 32bit int max

**Comment by bocklund** [comment]
There's also nothing about 6442 or 6443 that are special. It also fails for `M = 5011`, which is smaller, but M*N > 2,147,483,647 still.

**Comment by moorepants** [comment]
Yes, Index is a C int and @bocklund is correct. I've seen some posts on the ipopt email list regarding very large problems. Maybe you should ask there for advice on your problem size. It may take some customizing of ipopt if it is possible.

**Comment by moorepants** [comment]
That said, the check and error message can be improved.

**Comment by moorepants** [comment]
@ForceBru will your Jacobian be sparse? If it is sparse and the number of non-zero elements is less that 2,147,483,647 then it should work. Your dummy problem assumes a dense Jacobian.

**Comment by ForceBru** [comment]
> @ForceBru will your Jacobian be sparse? If it is sparse and the number of non-zero elements is less than 2,147,483,647 then it should work. Your dummy problem assumes a dense Jacobian.

Yeah, I've just realised that it should be sparse and I could allocate much less memory
