### ISSUE TITLE
Usage example for README.srt

### ISSUE THREAD

**Issue by pollinico** [mechmotum/cyipopt#96]
Hi, a small thing.
I believe that the simple example of usage of cyipopt (for the readme) that works currently is:
`from scipy.optimize import rosen, rosen_der`  
`from ipopt import minimize_ipopt`  
`x0 = [1.3, 0.7, 0.8, 1.9, 1.2]`  
`res = minimize_ipopt(rosen, x0, jac=rosen_der)`  
`print(res)`

**Comment by moorepants** [comment]
The code you share is from the last release of cyipopt. The master branch (the REAMDE you see here) has a new API which will be in the next release. The REAMDE shown by default here is for the development version not the released version.

**Comment by moorepants** [comment]
Closing this, as it will be resolved on release of the next version. See #94.
