### ISSUE TITLE
Conda install of cyipopt in Windows

### ISSUE THREAD

**Issue by pollinico** [mechmotum/cyipopt#97]
Hi guys, it's me again :-) !
Just a small comment: I noticed that in the README.srt you say that ` conda install -c conda-forge cyipopt ` does not work for Windows. I actually installed it that way on Windows and it seems to work well. Am I missing something?
Thanks for your attention.
All the best,
Nicolò

**Comment by moorepants** [comment]
The README just hasn't been updated. Thanks.

**Comment by moorepants** [comment]
Closing in favor of #94.
