### ISSUE TITLE
sparse jacobian with SciPy interface

### ISSUE THREAD

**Issue by yunlongxu-artemis** [mechmotum/cyipopt#98]
Hi there, is it possible that the SciPy interface does not handle sparse jacobian at the moment? (while the default interface of ipopt.Problem does) 

For example [here](https://github.com/mechmotum/cyipopt/blob/5b5e11db4f0f0b93c6d95ec68e6ecb6b394141e3/cyipopt/scipy_interface.py#L137), this would probably only work with dense jacobian, right?

I'm interested in the SciPy interface due to two factors:
1) better abstraction of my code to be solver independent
2) get the number of iterations... (somehow with the other interface, that information is not returned, but it seems like with the SciPy interface it is)

**Comment by moorepants** [comment]
The SciPy interface only supports dense Jacobians. We welcome any additions to make it otherwise.
