### ISSUE TITLE
Support for hessians in the scipy interface

### ISSUE THREAD

**Issue by jhelgert** [mechmotum/cyipopt#99]
It's commonly known that providing exact hessians can speed up IPOPT's convergence significantly. Unfortunately, there's no way to pass hessians to the scipy interface, see [here](https://github.com/mechmotum/cyipopt/blob/master/cyipopt/scipy_interface.py#L76). I could provide a PR. Just let me know. :)

**Comment by moorepants** [comment]
A PR is welcome. If scipy.optimize.minimize accepts Hessains, then we should mimic their interface.

**Comment by jhelgert** [comment]
> If scipy.optimize.minimize accepts Hessains, then we should mimic their interface.

Totally agree.

As soon as I finished my master's thesis, I start working on a PR. I guess it will be at the end of April at the earliest.

**Comment by moorepants** [comment]
Sounds great. Looking forward to it.

**Comment by jhelgert** [comment]
I totally forgot about it but will get on it next weekend. Just a little reminder for myself. :)

**Comment by jhelgert** [comment]
@moorepants Sorry for the delay. I finally had time to work on a PR. 

At the moment, cyipopt's scipy interface only accepts dictionary constraints whereas [`scipy.optimize.minimize`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html) also accepts (the newer) [`NonlinearConstraint`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.NonlinearConstraint.html) objects. However, the former doesn't support a `hess` field, so one can't pass Hessians through a dictionary constraint. AFAIK, the latter was added with the 'trust-constr' method which is also the only method that supports both objective and constraint hessians.

We can either

1. Simply support a `hess` field for the dictionary constraints contrary to scipy and skip NonlinearConstraints for the moment. If so, I can also submit a PR to scipy that adds the same behaviour. (Disclaimer, I prefer dictionary constraints)
2. Directly implement support for NonlinearConstraints similar to scipy, i.e. no `hess` field for dictionary constraints.
3. The intersection of 1. and 2., i.e. add support dictionary constraint Hessians and NonlinearConstraints.

What do you think?

**Comment by moorepants** [comment]
I think it is ok for us to have the `hess` field in the dictionary even though scipy doesn't. Our interface should work with inputs that SciPy's does, but we don't necessarily have to support the opposite.
